Fix broken wmpaws.run_sql
Due to libraries update, the previous
code started to error out with

AttributeError: OptionEngine object has no attribute execute